# Generated by Django 2.0.3 on 2018-04-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
