# Generated by Django 2.0.3 on 2018-04-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_remove_show_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='example',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='show',
            name='hit',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
